<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION ARTIFICIAL   (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date | custom)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION STATUS    	( UNKNOWN | SKIPPED | UNSUPPORTED | FAILURE | PARTIAL | APPLIED | APPLIED_OTHER )	#IMPLIED>
  <!-- STATUS defaults to APPLIED if BYTES specified and TYPE is non-zero  -->
  <!-- STATUS defaults to APPLIED_OTHER if BYTES specified and TYPE is zero  -->
  <!-- STATUS defaults to UNKNOWN if BYTES are not specified  -->
  <!ATTLIST RELOCATION TYPE     	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION VALUE    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION BYTES    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION SYMBOL_NAME	CDATA	#IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY COMMENT  CDATA  #REQUIRED>

]>
<PROGRAM NAME="X6100_BBFW_V1.1.6_221112001.bin" EXE_PATH="/opt/ghidra_11.1.2_PUBLIC/X6100_BBFW_V1.1.6_221112001.bin" EXE_FORMAT="STM32 Loader (Standard Peripheral Library)" IMAGE_BASE="00000000">
    <INFO_SOURCE USER="tush" TOOL="Ghidra 11.1.2" TIMESTAMP="Tue May 27 09:43:31 MSK 2025" />
    <PROCESSOR NAME="ARM" LANGUAGE_PROVIDER="ARM:LE:32:Cortex:default" ENDIAN="little" />
    <DATATYPES>
        <FUNCTION_DEF NAME="__adjust" NAMESPACE="/std.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="double" DATATYPE_NAMESPACE="/" SIZE="0x8" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_reent *" DATATYPE_NAMESPACE="/reent.h" NAME="ptr" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="double *" DATATYPE_NAMESPACE="/" NAME="acc" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="dexp" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="sign" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__any_on" NAMESPACE="/mprec.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="__ULong" DATATYPE_NAMESPACE="/reent.h" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_Bigint *" DATATYPE_NAMESPACE="/reent.h" NAME="b" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="k" SIZE="0x4" />
        </FUNCTION_DEF>
        <ENUM NAME="__atexit_types" NAMESPACE="/atexit.h" SIZE="0x4">
            <ENUM_ENTRY NAME="__et_atexit" VALUE="0x0" COMMENT="" />
            <ENUM_ENTRY NAME="__et_onexit" VALUE="0x1" COMMENT="" />
            <ENUM_ENTRY NAME="__et_cxa" VALUE="0x2" COMMENT="" />
        </ENUM>
        <FUNCTION_DEF NAME="__b2d" NAMESPACE="/mprec.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="double" DATATYPE_NAMESPACE="/" SIZE="0x8" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_Bigint *" DATATYPE_NAMESPACE="/reent.h" NAME="a" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="int *" DATATYPE_NAMESPACE="/" NAME="e" SIZE="0x4" />
        </FUNCTION_DEF>
        <TYPE_DEF NAME="__blkcnt_t" NAMESPACE="/types.h" DATATYPE="long" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__blksize_t" NAMESPACE="/types.h" DATATYPE="long" DATATYPE_NAMESPACE="/" />
        <FUNCTION_DEF NAME="__bswap16" NAMESPACE="/endian.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="__uint16_t" DATATYPE_NAMESPACE="/types.h" SIZE="0x2" />
            <PARAMETER ORDINAL="0x0" DATATYPE="__uint16_t" DATATYPE_NAMESPACE="/types.h" NAME="_x" SIZE="0x2" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__bswap32" NAMESPACE="/endian.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="__uint32_t" DATATYPE_NAMESPACE="/types.h" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="__uint32_t" DATATYPE_NAMESPACE="/types.h" NAME="_x" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__bswap64" NAMESPACE="/endian.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="__uint64_t" DATATYPE_NAMESPACE="/types.h" SIZE="0x8" />
            <PARAMETER ORDINAL="0x0" DATATYPE="__uint64_t" DATATYPE_NAMESPACE="/types.h" NAME="_x" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__call_exitprocs" NAMESPACE="/atexit.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <TYPE_DEF NAME="__clock_t" NAMESPACE="/_types.h" DATATYPE="ulong" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__clockid_t" NAMESPACE="/_types.h" DATATYPE="ulong" DATATYPE_NAMESPACE="/" />
        <FUNCTION_DEF NAME="__copybits" NAMESPACE="/mprec.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="__ULong *" DATATYPE_NAMESPACE="/reent.h" NAME="c" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="n" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="_Bigint *" DATATYPE_NAMESPACE="/reent.h" NAME="b" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__cp_index" NAMESPACE="/local.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__cp_val_index" NAMESPACE="/local.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__ctype_load_locale" NAMESPACE="/setlocale.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="__locale_t *" DATATYPE_NAMESPACE="/reent.h" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x4" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__current_locale_charset" NAMESPACE="/setlocale.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__d2b" NAMESPACE="/mprec.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="_Bigint *" DATATYPE_NAMESPACE="/reent.h" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_reent *" DATATYPE_NAMESPACE="/reent.h" NAME="p" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="double" DATATYPE_NAMESPACE="/" NAME="d" SIZE="0x8" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int *" DATATYPE_NAMESPACE="/" NAME="e" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="int *" DATATYPE_NAMESPACE="/" NAME="bits" SIZE="0x4" />
        </FUNCTION_DEF>
        <TYPE_DEF NAME="__daddr_t" NAMESPACE="/_types.h" DATATYPE="long" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__dev_t" NAMESPACE="/_types.h" DATATYPE="short" DATATYPE_NAMESPACE="/" />
        <FUNCTION_DEF NAME="__dorand48" NAMESPACE="/rand48.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_reent *" DATATYPE_NAMESPACE="/reent.h" NAME="r" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="ushort[3]" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x6" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__dtoa" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_reent *" DATATYPE_NAMESPACE="/reent.h" NAME="ptr" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="double" DATATYPE_NAMESPACE="/" NAME="d" SIZE="0x8" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="mode" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="ndigits" SIZE="0x4" />
            <PARAMETER ORDINAL="0x4" DATATYPE="int *" DATATYPE_NAMESPACE="/" NAME="decpt" SIZE="0x4" />
            <PARAMETER ORDINAL="0x5" DATATYPE="int *" DATATYPE_NAMESPACE="/" NAME="sign" SIZE="0x4" />
            <PARAMETER ORDINAL="0x6" DATATYPE="char * *" DATATYPE_NAMESPACE="/" NAME="rve" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__errno" NAMESPACE="/errno.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__exp10" NAMESPACE="/std.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="double" DATATYPE_NAMESPACE="/" SIZE="0x8" />
            <PARAMETER ORDINAL="0x0" DATATYPE="uint" DATATYPE_NAMESPACE="/" NAME="x" SIZE="0x4" />
        </FUNCTION_DEF>
        <TYPE_DEF NAME="__fd_mask" NAMESPACE="/select.h" DATATYPE="ulong" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__FILE" NAMESPACE="/reent.h" DATATYPE="__sFILE" DATATYPE_NAMESPACE="/reent.h" />
        <FUNCTION_DEF NAME="__freedtoa" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_reent *" DATATYPE_NAMESPACE="/reent.h" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <TYPE_DEF NAME="__fsblkcnt_t" NAMESPACE="/_types.h" DATATYPE="__uint64_t" DATATYPE_NAMESPACE="/types.h" />
        <TYPE_DEF NAME="__fsfilcnt_t" NAMESPACE="/_types.h" DATATYPE="__uint32_t" DATATYPE_NAMESPACE="/types.h" />
        <FUNCTION_DEF NAME="__g_ddfmt" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="double *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="size_t" DATATYPE_NAMESPACE="/stddef.h" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__g_dfmt" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="double *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="size_t" DATATYPE_NAMESPACE="/stddef.h" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__g_ffmt" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="float *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="size_t" DATATYPE_NAMESPACE="/stddef.h" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__g_Qfmt" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="size_t" DATATYPE_NAMESPACE="/stddef.h" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__g_xfmt" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="size_t" DATATYPE_NAMESPACE="/stddef.h" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__g_xLfmt" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="size_t" DATATYPE_NAMESPACE="/stddef.h" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__gdtoa" NAMESPACE="/gdtoa.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="char *" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_reent *" DATATYPE_NAMESPACE="/reent.h" NAME="ptr" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="FPI *" DATATYPE_NAMESPACE="/mprec.h" NAME="fpi" SIZE="0x4" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="be" SIZE="0x4" />
            <PARAMETER ORDINAL="0x3" DATATYPE="__ULong *" DATATYPE_NAMESPACE="/reent.h" NAME="bits" SIZE="0x4" />
            <PARAMETER ORDINAL="0x4" DATATYPE="int *" DATATYPE_NAMESPACE="/" NAME="kindp" SIZE="0x4" />
            <PARAMETER ORDINAL="0x5" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="mode" SIZE="0x4" />
            <PARAMETER ORDINAL="0x6" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="ndigits" SIZE="0x4" />
            <PARAMETER ORDINAL="0x7" DATATYPE="int *" DATATYPE_NAMESPACE="/" NAME="decpt" SIZE="0x4" />
            <PARAMETER ORDINAL="0x8" DATATYPE="char * *" DATATYPE_NAMESPACE="/" NAME="rve" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__get_C_locale" NAMESPACE="/setlocale.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="__locale_t *" DATATYPE_NAMESPACE="/reent.h" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="__get_current_locale" NAMESPACE="/setlocale.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>